extends:
  import: classic
  file: go/pipeline.yaml
pipelines:
  pullRequest:
    build:
      steps:
      - sh: export VERSION=$PREVIEW_VERSION && skaffold build -f skaffold.yaml
    postBuild:
      steps:
      - sh: jx step post build --image $DOCKER_REGISTRY/$ORG/$APP_NAME:$PREVIEW_VERSION
    promote:
      steps:
      - dir: /home/jenkins/go/src/REPLACE_ME_GIT_PROVIDER/REPLACE_ME_ORG/REPLACE_ME_APP_NAME/charts/preview
        steps:
        - sh: make preview
          name: make-preview
          image: 702769831180.dkr.ecr.ap-south-1.amazonaws.com/702769831180/jxl
        - sh: jx preview --app $APP_NAME --dir ../..
          name: make-preview
          image: 702769831180.dkr.ecr.ap-south-1.amazonaws.com/702769831180/jxl

  release:
    build:
      steps:
      - sh: export VERSION=`cat VERSION` && skaffold build -f skaffold.yaml
      - sh: jx step post build --image $DOCKER_REGISTRY/$ORG/$APP_NAME:\$(cat VERSION)
    promote:
      steps:
      - dir: /home/jenkins/go/src/REPLACE_ME_GIT_PROVIDER/REPLACE_ME_ORG/REPLACE_ME_APP_NAME/charts/REPLACE_ME_APP_NAME
        steps:
        - sh: jx step changelog --version v\$(cat ../../VERSION)
          image: 702769831180.dkr.ecr.ap-south-1.amazonaws.com/702769831180/jxl
        - comment: release the helm chart
          sh: jx step helm release
          image: 702769831180.dkr.ecr.ap-south-1.amazonaws.com/702769831180/jxl
        - comment: promote through all 'Auto' promotion Environments
          sh: jx promote -b --all-auto --timeout 1h --version \$(cat ../../VERSION)
          image: 702769831180.dkr.ecr.ap-south-1.amazonaws.com/702769831180/jxl
